; Enable error logging
log_errors = On

; Report all errors
error_reporting = E_ALL

; Do not display errors in the browser output for security
display_errors = On

; Send logs to stderr, which is the standard for Docker containers
; This allows 'docker logs' to capture PHP errors.
error_log = /var/log/php/error.log

; Xdebug Configuration
[xdebug]
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.start_with_request=trigger
xdebug.client_host=host.docker.internal
xdebug.client_port=9004
xdebug.idekey=PHPSTORM
xdebug.log=/var/log/php/xdebug.log
xdebug.output_dir=/tmp/xdebug
xdebug.max_nesting_level=500
